### ISSUE TITLE
Unexpected token ... on 2.8.0 (Meteor 1.5.2)

### ISSUE THREAD

**Issue by wojtkowiak** [nathantreid/meteor-css-modules#107]
After updating from 2.7.4 to 2.8 I got this error. I've compared the code and it seems that the contents of the build plugins were not transpiled so they do not work on node 4.... I guess that this is a bug in Meteor and you need to publish the plugin with Meteor 1.5.x 

```
=> Started MongoDB.

Changes to your project's package version selections:

nathantreid:css-modules  upgraded from 2.7.4 to 2.8.0

=> Errors prevented startup:

   While loading plugin `mss` from package `nathantreid:css-modules`:
   vm.js:24:10: Unexpected token ...
   at Object.exports.createScript (vm.js:24:10)
   at C:\tools\fs\files.js:1162:34
   at Function.time (C:\tools\tool-env\profile.js:305:10)
   at Object.files.runJavaScript (C:\tools\fs\files.js:1100:18)
   at C:\tools\isobuild\bundler.js:1973:15
   at Array.forEach (native)
   at Function._.each._.forEach
   (C:\Users\omega\AppData\Local\.meteor\packages\meteor-tool\1.5.2_2\mt-os.windows.x86_32\dev_b
undle\lib\node_modules\underscore\underscore.js:79:11)
   at JsImage.load (C:\tools\isobuild\bundler.js:1858:7)
   at C:\tools\isobuild\isopack.js:536:16
   at C:\tools\utils\buildmessage.js:359:18
   at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
   at C:\tools\utils\buildmessage.js:352:34
   at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
   at C:\tools\utils\buildmessage.js:350:23
   at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
   at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
   at C:\tools\isobuild\isopack.js:526:20
   at Function._.each._.forEach
   (C:\Users\omega\AppData\Local\.meteor\packages\meteor-tool\1.5.2_2\mt-os.windows.x86_32\dev_b
undle\lib\node_modules\underscore\underscore.js:87:22)
   at [object Object].ensurePluginsInitialized (C:\tools\isobuild\isopack.js:514:7)
   at C:\tools\isobuild\compiler.js:382:16
   at Array.forEach (native)
   at C:\tools\isobuild\compiler.js:381:26
   at C:\tools\utils\buildmessage.js:359:18
   at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
   at C:\tools\utils\buildmessage.js:352:34
   at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
   at C:\tools\utils\buildmessage.js:350:23
   at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
   at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
   at C:\tools\isobuild\compiler.js:377:16
   at C:\tools\isobuild\compiler.js:184:28
   at Object.withCache (C:\tools\fs\files.js:1694:12)
   at C:\tools\isobuild\compiler.js:183:11
   at Array.forEach (native)
   at Function._.each._.forEach
   (C:\Users\omega\AppData\Local\.meteor\packages\meteor-tool\1.5.2_2\mt-os.windows.x86_32\dev_b
undle\lib\node_modules\underscore\underscore.js:79:11)
   at Object.compile (C:\tools\isobuild\compiler.js:178:5)
   at C:\tools\isobuild\bundler.js:2956:24
   at C:\tools\utils\buildmessage.js:271:13
   at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
   at C:\tools\utils\buildmessage.js:264:29
   at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
   at C:\tools\utils\buildmessage.js:262:18
   at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
   at C:\tools\utils\buildmessage.js:253:23
   at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
   at Object.capture (C:\tools\utils\buildmessage.js:252:19)
   at bundle (C:\tools\isobuild\bundler.js:2899:31)
   at C:\tools\isobuild\bundler.js:2846:32
   at Object.withCache (C:\tools\fs\files.js:1694:12)
   at Object.exports.bundle (C:\tools\isobuild\bundler.js:2846:16)
   at C:\tools\runners\run-app.js:583:36
   at Function.run (C:\tools\tool-env\profile.js:490:12)
   at bundleApp (C:\tools\runners\run-app.js:582:34)
   at [object Object]._.extend._runOnce (C:\tools\runners\run-app.js:626:35)
   at [object Object]._.extend._fiber (C:\tools\runners\run-app.js:885:28)
   at C:\tools\runners\run-app.js:412:12
```

**Comment by wojtkowiak** [comment]
Ok, you need to maintain a separate version line and publish with 1.5 if you want to support pre 1.6 versions.
https://github.com/meteor/meteor/issues/9308

**Comment by akanix42** [comment]
OK, thanks! I'll publish 2.8.1 soon with Meteor 1.5 support and bump to 3.0.0 for 1.6.

**Comment by akanix42** [comment]
Closing because the separate versions were published a while ago.

**Comment by wojtkowiak** [comment]
Yep, thanks :)

**Comment by wojtkowiak** [comment]
FYI: missing 2.8.1 3.0.0 tags in the repo

**Comment by akanix42** [comment]
Added tags and CHANGELOG entries, thanks.
