### ISSUE TITLE
'TypeError: Cannot read property '_diskCache' of undefined' error with Meteor 1.8.0.2 / meteor-css-modules 3.2.3-beta.1

### ISSUE THREAD

**Issue by shenrenguo** [nathantreid/meteor-css-modules#126]
When building the meteor app (Meteor 1.8.02 / meteor-css-modules 3.2.3-beta.1), I get the following error :

/~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Processing Step: Babel compilation
Unable to compile node_modules/react-toolbox/lib/app_bar/config.css
TypeError: Cannot read property '_diskCache' of undefined
Source:
// <start of file>

// <end of file>

/~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

/~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Processing Step: Babel compilation
Unable to compile node_modules/react-toolbox/lib/app_bar/config.css
TypeError: Cannot read property '_diskCache' of undefined
Source:
// <start of file>

// <end of file>

/~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
(node:33227) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '_diskCache' of undefined
    at tryBabelCompile (packages/mss/css-modules-build-plugin.js:255:47)
    at CssModulesBuildPlugin._generateOutput (packages/mss/css-modules-build-plugin.js:231:9)
    at CssModulesBuildPlugin.compileOneFile (packages/mss/css-modules-build-plugin.js:168:32)
    at getResult (packages/caching-compiler/multi-file-caching-compiler.js:113:32)
    at inputFiles.forEach.inputFile (packages/caching-compiler/multi-file-caching-compiler.js:167:24)
    at Array.forEach (<anonymous>)
    at Promise.asyncApply (packages/caching-compiler/multi-file-caching-compiler.js:93:16)
    at /Users/srg/.meteor/packages/meteor-tool/.1.8.0_2.1e13e9t.e06e++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/fiber_pool.js:43:40

**Comment by akanix42** [comment]
This is a duplicate of #124. I just pushed what seems to be a fix - please try `nathantreid:css-modules@3.2.3-beta.3`.

**Comment by shenrenguo** [comment]
it's work
thx

> This is a duplicate of #124. I just pushed what seems to be a fix - please try `nathantreid:css-modules@3.2.3-beta.3`.
