### ISSUE TITLE
[beta5] Error when files are in multiple path

### ISSUE THREAD

**Issue by dagatsoin** [nathantreid/meteor-css-modules#2]
I have an error which seems appears when I change files path:

```
=> Started proxy.                             
=> Started MongoDB.                           
=> Errors prevented startup:                  

   While processing files with nathantreid:css-modules (for target web.browser):
   /Users/vikti/.meteor/packages/meteor-tool/.1.1.13-modules.8.1jogvta++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/static-assets/server/mini-files.js:67:23: Cannot call method 'replace'
   of undefined
   at Object.convertToStandardLineEndings
   (/Users/vikti/.meteor/packages/meteor-tool/.1.1.13-modules.8.1jogvta++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/static-assets/server/mini-files.js:67:23)
   at ResourceSlot.addStylesheet (/tools/isobuild/compiler-plugin.js:406:24)
   at InputFile.addStylesheet (/tools/isobuild/compiler-plugin.js:253:24)
   at packages/css-modules-build-plugin/css-modules-build-plugin.js:23:10
   at /Users/vikti/.meteor/packages/templating/.1.1.6-modules.8.1tmw96o++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/promise/node_modules/meteor-promise/fiber_pool.js:33:40


=> Your application has errors. Waiting for file change.
```

I  made a repo for this: https://github.com/dagatsoin/css-modules-bug00-beta5

**Comment by akanix42** [comment]
Thanks, I'll take a look at it.

**Comment by akanix42** [comment]
This is fixed in the latest release, nathantreid:css-modules@1.0.0-beta.6 (which should be up on Atmosphere momentarily).
