### ISSUE TITLE
TypeError: Cannot call method 'substr' of undefined

### ISSUE THREAD

**Issue by gadicc** [nathantreid/meteor-css-modules#23]
Have you come across this before?

Running a checkout from master now on Meteor 1.3.2.2.  The last files were:

```
ip: ~normalize.css
rt: /home/dragon/www/projects/wmd2/supervisor/node_modules/react-toolbox/lib/commons.scss
```

But I don't see anything strange with [commons.scss](https://github.com/react-toolbox/react-toolbox/blob/master/components/commons.scss), I'm guessing the problem is in the merge.

<details>
<summary>

`TypeError: Cannot call method 'substr' of undefined` (in source-map)</summary>

```
/home/dragon/.meteor/packages/less/.2.6.0.1l2fur5++os+web.browser+web.cordova/plugin.compileLessBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^

[gadicc:hot] Accelerator(1): disconnect event received, exiting.
TypeError: Cannot call method 'substr' of undefined
    at Function.<anonymous> (/home/dragon/.meteor/packages/meteor-tool/.1.3.2_2.1icvioz++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/source-map/lib/source-node.js:115:29)
    at Array.forEach (native)
    at SourceMapConsumer_eachMapping [as eachMapping] (/home/dragon/.meteor/packages/meteor-tool/.1.3.2_2.1icvioz++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/source-map/lib/source-map-consumer.js:155:16)
    at Function.SourceNode_fromStringWithSourceMap [as fromStringWithSourceMap] (/home/dragon/.meteor/packages/meteor-tool/.1.3.2_2.1icvioz++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/source-map/lib/source-node.js:80:26)
    at getChunk (/tools/isobuild/import-scanner.js:291:20)
    at ImportScanner._combineFiles (/tools/isobuild/import-scanner.js:299:7)
    at /tools/isobuild/import-scanner.js:187:14
    at Array.forEach (native)
    at ImportScanner.addInputFiles (/tools/isobuild/import-scanner.js:158:11)
    at /tools/isobuild/compiler-plugin.js:834:15
    at Array.forEach (native)
    at Function.computeJsOutputFilesMap (/tools/isobuild/compiler-plugin.js:805:19)
    at ClientTarget._emitResources (/tools/isobuild/bundler.js:913:8)
    at /tools/isobuild/bundler.js:684:12
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ClientTarget.make (/tools/isobuild/bundler.js:675:18)
    at /tools/isobuild/bundler.js:2474:14
    at /tools/isobuild/bundler.js:2563:20
    at Array.forEach (native)
    at Function._.each._.forEach (/home/dragon/.meteor/packages/meteor-tool/.1.3.2_2.1icvioz++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/bundler.js:2562:7
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2455:31)
    at /tools/runners/run-app.js:591:36
    at Function.run (/tools/tool-env/profile.js:489:12)
    at bundleApp (/tools/runners/run-app.js:581:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:634:35)
    at AppRunner._fiber (/tools/runners/run-app.js:887:28)
    at /tools/runners/run-app.js:411:12
```

</details>

That line in `source-map` btw is [here](https://github.com/mozilla/source-map/blob/master/lib/source-node.js#L115).

I don't use css-modules anywhere else in my code, so I'm guessing the issue is with react-toolbox.  Maybe you'll come across it when upgrading https://github.com/nathantreid/meteor-react-toolbox-example.

**Comment by akanix42** [comment]
I've seen this issue before when I was adding 2 different files with the same name (while fixing a fug - it wasn't something you could do in your own project). My guess is this is a similar issue because 1.3.2.2 supports importing scss files from node modules directly, which hopefully means we no longer need the `explicitIncludes` option.

**Comment by gadicc** [comment]
Thanks, I'm going to move this issue to https://github.com/nathantreid/meteor-react-toolbox-example/issues/4.
