### ISSUE TITLE
Unable to change default font family in css-modules/react-toolbox

### ISSUE THREAD

**Issue by dfischer** [nathantreid/meteor-css-modules#25]
I get a weird error (looks like a hanging quote for some reason)

Source:
`$preferred-font: BlinkMacSystemFont, "Helvetica Neue";`

```
Your app is crashing. Here's the latest log:


While processing files with nathantreid:css-modules (for target web.browser):
<anonymous>: Unexpected token 'e' at 3:41
"preferred-font":"BlinkMacSystemFont, "Helvetica Neue""}
                                        ^
  at SyntaxError (<anonymous>)
  at Object.parseJSON (/Users/daniel/.meteor/packages/nathantreid_css-modules/.1.1.1.13680tq++os.osx.x86_64+web.browser+web.cordova/plugin.mss.os.osx.x86_64/npm/node_modules/meteor/mss/node_modules/cjson/node_modules/json-parse-helpfulerror/node_modules/jju/lib/parse.js:745:13)
  at Object.parse (/Users/daniel/.meteor/packages/nathantreid_css-modules/.1.1.1.13680tq++os.osx.x86_64+web.browser+web.cordova/plugin.mss.os.osx.x86_64/npm/node_modules/meteor/mss/node_modules/cjson/node_modules/json-parse-helpfulerror/index.js:10:13)
  at exports.parse (/Users/daniel/.meteor/packages/nathantreid_css-modules/.1.1.1.13680tq++os.osx.x86_64+web.browser+web.cordova/plugin.mss.os.osx.x86_64/npm/node_modules/meteor/mss/node_modules/cjson/index.js:90:28)
  at packages/ramda_ramda.js:300:22
  at packages/ramda_ramda.js:89:27
  at convertScssVariablesToJsonVariables (packages/mss/options.js:79:10)
  at packages/mss/options.js:55:29
  at Array.forEach (native)
  at processGlobalVariables (packages/mss/options.js:42:26)
  at loadOptions (packages/mss/options.js:31:12)
  at CssModulesBuildPlugin.processFilesForTarget (packages/mss/css-modules-build-plugin.js:48:19)


Your application has errors. Waiting for file change.
```

**Comment by akanix42** [comment]
I parse the global variables as json to make them accessible from javascript.. I'll need to adjust the parsing or allow it to be disabled so it doesn't break when things like this happen.

**Comment by dfischer** [comment]
Yeah just trying to customize react-toolbox. Found a way to get around it for now by hacking the css. 👍
