### ISSUE TITLE
Error after upgrading from 1.0.3 to 1.1.1

### ISSUE THREAD

**Issue by johnnynotsolucky** [nathantreid/meteor-css-modules#28]
After updating Meteor to 1.3.2.4, `css-modules` was auto-upgraded to 1.1.1 from 1.0.3. 

When I try to run the project, I get the following error

```
=> Started proxy.
=> Started MongoDB.

C:\Users\John\AppData\Local\.meteor\packages\templating\1.1.9\plugin.compileTemplatesBatch.os\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:116
    throw error;
      ^
TypeError: Cannot call method 'substr' of undefined
  at Function.<anonymous> (C:\Users\John\AppData\Local\.meteor\packages\meteor-tool\1.3.2_4\mt-os.windows.x86_32\dev_bundle\lib\node_modules\source-map\lib\source-node.js:115:29)
  at Array.forEach (native)
  at SourceMapConsumer_eachMapping [as eachMapping] (C:\Users\John\AppData\Local\.meteor\packages\meteor-tool\1.3.2_4\mt-os.windows.x86_32\dev_bundle\lib\node_modules\source-map\lib\source-map-consumer.js:155:16)
  at Function.SourceNode_fromStringWithSourceMap [as fromStringWithSourceMap] (C:\Users\John\AppData\Local\.meteor\packages\meteor-tool\1.3.2_4\mt-os.windows.x86_32\dev_bundle\lib\node_modules\source-map\lib\source-node.js:80:26)
  at getChunk (C:\tools\isobuild\import-scanner.js:291:20)
  at ImportScanner._combineFiles (C:\tools\isobuild\import-scanner.js:299:7)
  at C:\tools\isobuild\import-scanner.js:187:14
  at Array.forEach (native)
  at ImportScanner.addInputFiles (C:\tools\isobuild\import-scanner.js:158:11)
  at C:\tools\isobuild\compiler-plugin.js:834:15
  at Array.forEach (native)
  at Function.computeJsOutputFilesMap (C:\tools\isobuild\compiler-plugin.js:805:19)
  at ClientTarget._emitResources (C:\tools\isobuild\bundler.js:913:8)
  at C:\tools\isobuild\bundler.js:684:12
  at C:\tools\utils\buildmessage.js:359:18
  at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
  at C:\tools\utils\buildmessage.js:352:34
  at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
  at C:\tools\utils\buildmessage.js:350:23
  at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
  at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
  at ClientTarget.make (C:\tools\isobuild\bundler.js:675:18)
  at C:\tools\isobuild\bundler.js:2474:14
  at C:\tools\isobuild\bundler.js:2563:20
  at Array.forEach (native)
  at Function._.each._.forEach (C:\Users\John\AppData\Local\.meteor\packages\meteor-tool\1.3.2_4\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
  at C:\tools\isobuild\bundler.js:2562:7
  at C:\tools\utils\buildmessage.js:271:13
  at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
  at C:\tools\utils\buildmessage.js:264:29
  at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
  at C:\tools\utils\buildmessage.js:262:18
  at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
  at C:\tools\utils\buildmessage.js:253:23
  at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
  at Object.capture (C:\tools\utils\buildmessage.js:252:19)
  at Object.exports.bundle (C:\tools\isobuild\bundler.js:2455:31)
  at C:\tools\runners\run-app.js:591:36
  at Function.run (C:\tools\tool-env\profile.js:489:12)
  at bundleApp (C:\tools\runners\run-app.js:581:34)
  at AppRunner._runOnce (C:\tools\runners\run-app.js:634:35)
  at AppRunner._fiber (C:\tools\runners\run-app.js:887:28)
  at C:\tools\runners\run-app.js:411:12
```

However, when I downgrade back to 1.0.3, everything works perfectly. Could this be a problem with my set up or a potential bug in the `css-modules` package?

**Comment by akanix42** [comment]
This has been fixed in 1.1.2.
