### ISSUE TITLE
[beta5] Use postcss-import

### ISSUE THREAD

**Issue by dagatsoin** [nathantreid/meteor-css-modules#3]
Do you manage to import a bunch of var in another file?
I am trying this file structure:

```
/* hello.mss */
@import "./font.mss";
.hello {
  font-size: $size;
}
```

```
/* variables.mss */
$size: 17px;

```

I have installed postcss-import and place it in first place in package.json

```

{
...
  "devDependencies": {
    "postcss-import": "^8.0.2",
    "postcss-modules-extract-imports": "1.0.0",
    "postcss-modules-local-by-default": "1.0.0",
    "postcss-modules-scope": "1.0.0",
    "postcss-modules-values": "1.1.1",
    "postcss-nested": "1.0.0",
    "postcss-simple-vars": "1.1.0"
  },
  "cssModules": {
    "plugins": {
      "postcss-import":{},
      "postcss-simple-vars": {},
      "postcss-modules-values": {},
      "postcss-nested": {},
      "postcss-modules-local-by-default": {},
      "postcss-modules-extract-imports": {},
      "postcss-modules-scope": {}
    }
  }
}


```

But ended with this error:

```
=> Errors prevented startup:

   While processing files with nathantreid:css-modules (for target web.browser):

   /Users/vikti/.meteor/packages/nathantreid_css-modules/.1.0.0-beta.5.wutujy++os+web.browser+web.cordova/plugin.css-modules-build-plugin.os/npm/css-modules-build-plugin/node_modules/postcss/lib/input.js:61:22:
   postcss-simple-vars: /Users/vikti/dev/css-modules-demo-meteor-1.3/{}/client/hello.mss:6:2: Undefined variable $size
   at Input.error
   (/Users/vikti/.meteor/packages/nathantreid_css-modules/.1.0.0-beta.5.wutujy++os+web.browser+web.cordova/plugin.css-modules-build-plugin.os/npm/css-modules-build-plugin/node_modules/postcss/lib/input.js:61:22)
   at Declaration.error
   (/Users/vikti/.meteor/packages/nathantreid_css-modules/.1.0.0-beta.5.wutujy++os+web.browser+web.cordova/plugin.css-modules-build-plugin.os/npm/css-modules-build-plugin/node_modules/postcss/lib/node.js:72:38)
   at Object.opts.unknown (/Users/vikti/dev/css-modules-demo-meteor-1.3/node_modules/postcss-simple-vars/index.js:72:24)
   at variable (/Users/vikti/dev/css-modules-demo-meteor-1.3/node_modules/postcss-simple-vars/index.js:24:24)
   at /Users/vikti/dev/css-modules-demo-meteor-1.3/node_modules/postcss-simple-vars/index.js:35:22
   at String.replace (native)
   at RegExp.<anonymous>
   (/Users/vikti/.meteor/packages/meteor-tool/.1.1.13-modules.8.1jogvta++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-ecmascript-runtime/node_modules/core-js/modules/$.fix-re-wks.js:15:48)
   at String.replace
   (/Users/vikti/.meteor/packages/meteor-tool/.1.1.13-modules.8.1jogvta++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-ecmascript-runtime/node_modules/core-js/modules/es6.regexp.replace.js:9:12)
   at simpleSyntax (/Users/vikti/dev/css-modules-demo-meteor-1.3/node_modules/postcss-simple-vars/index.js:34:16)
   at bothSyntaxes (/Users/vikti/dev/css-modules-demo-meteor-1.3/node_modules/postcss-simple-vars/index.js:46:11)
   at declValue (/Users/vikti/dev/css-modules-demo-meteor-1.3/node_modules/postcss-simple-vars/index.js:52:18)
   at /Users/vikti/dev/css-modules-demo-meteor-1.3/node_modules/postcss-simple-vars/index.js:96:21
   at
   /Users/vikti/.meteor/packages/nathantreid_css-modules/.1.0.0-beta.5.wutujy++os+web.browser+web.cordova/plugin.css-modules-build-plugin.os/npm/css-modules-build-plugin/node_modules/postcss/lib/container.js:73:26
   at Rule.each
   (/Users/vikti/.meteor/packages/nathantreid_css-modules/.1.0.0-beta.5.wutujy++os+web.browser+web.cordova/plugin.css-modules-build-plugin.os/npm/css-modules-build-plugin/node_modules/postcss/lib/container.js:60:22)
   at Rule.walk
   (/Users/vikti/.meteor/packages/nathantreid_css-modules/.1.0.0-beta.5.wutujy++os+web.browser+web.cordova/plugin.css-modules-build-plugin.os/npm/css-modules-build-plugin/node_modules/postcss/lib/container.js:72:21)
   at
   /Users/vikti/.meteor/packages/nathantreid_css-modules/.1.0.0-beta.5.wutujy++os+web.browser+web.cordova/plugin.css-modules-build-plugin.os/npm/css-modules-build-plugin/node_modules/postcss/lib/container.js:76:32
   at Root.each
   (/Users/vikti/.meteor/packages/nathantreid_css-modules/.1.0.0-beta.5.wutujy++os+web.browser+web.cordova/plugin.css-modules-build-plugin.os/npm/css-modules-build-plugin/node_modules/postcss/lib/container.js:60:22)
   at Root.walk
   (/Users/vikti/.meteor/packages/nathantreid_css-modules/.1.0.0-beta.5.wutujy++os+web.browser+web.cordova/plugin.css-modules-build-plugin.os/npm/css-modules-build-plugin/node_modules/postcss/lib/container.js:72:21)
   at /Users/vikti/dev/css-modules-demo-meteor-1.3/node_modules/postcss-simple-vars/index.js:92:13
   at LazyResult.run
   (/Users/vikti/.meteor/packages/nathantreid_css-modules/.1.0.0-beta.5.wutujy++os+web.browser+web.cordova/plugin.css-modules-build-plugin.os/npm/css-modules-build-plugin/node_modules/postcss/lib/lazy-result.js:206:20)
   at
   /Users/vikti/.meteor/packages/nathantreid_css-modules/.1.0.0-beta.5.wutujy++os+web.browser+web.cordova/plugin.css-modules-build-plugin.os/npm/css-modules-build-plugin/node_modules/postcss/lib/lazy-result.js:120:37
   at LazyResult.asyncTick
   (/Users/vikti/.meteor/packages/nathantreid_css-modules/.1.0.0-beta.5.wutujy++os+web.browser+web.cordova/plugin.css-modules-build-plugin.os/npm/css-modules-build-plugin/node_modules/postcss/lib/lazy-result.js:134:15)
   at promise.then.catch._this.processed
   (/Users/vikti/.meteor/packages/nathantreid_css-modules/.1.0.0-beta.5.wutujy++os+web.browser+web.cordova/plugin.css-modules-build-plugin.os/npm/css-modules-build-plugin/node_modules/postcss/lib/lazy-result.js:125:31)
   at /Users/vikti/.meteor/packages/templating/.1.1.6-modules.8.1tmw96o++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/promise/node_modules/meteor-promise/fiber_pool.js:33:40


=> Your application has errors. Waiting for file change.
```

Here is a repo: https://github.com/dagatsoin/css-modules-bug01-beta5.git

**Comment by akanix42** [comment]
This is caused by the way I'm processing paths. I'm reconsidering the way I do that as part of the update to Meteor 1.3, so this might get fixed along the way.
Unfortunately the only workaround for now is to back out of the project directory, like so: 
@import '../../client/variables.mss';

Note that there is an extra ../ that what you would expect.

I'm also looking into adding pre-processor support (SASS, LESS, etc) but life is pretty busy right now so I'm not sure when I'll get around to that.

**Comment by akanix42** [comment]
This was fixed somewhere along the way, and is currently working in v2.2.2.
