### ISSUE TITLE
`addStyles` Error when importing in package

### ISSUE THREAD

**Issue by RafaelVidaurre** [nathantreid/meteor-css-modules#54]
My setup works in my main app but 2 things are not working for me:
- ~~The package doesn't seem to be reading from `package.json` it basically ignores my configs and sticks to defaults.~~ EDIT: This works when restarting the app
## When I try to import the file in a local package I get this error:

```
W20160710-22:12:19.299(-3)? (STDERR) TypeError: Object [object Object] has no method 'addStyles'
W20160710-22:12:19.299(-3)? (STDERR)     at meteorInstall.node_modules.meteor.pathable-styles.imports.test.m.css (node_modules/meteor/pathable-styles/imports/test.m.css:1:1)
W20160710-22:12:19.300(-3)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
W20160710-22:12:19.300(-3)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
W20160710-22:12:19.300(-3)? (STDERR)     at meteorInstall.node_modules.meteor.pathable-styles.pathable-styles.js (packages/pathable-styles/pathable-styles.js:2:1)
W20160710-22:12:19.300(-3)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
W20160710-22:12:19.300(-3)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
W20160710-22:12:19.300(-3)? (STDERR)     at node_modules/meteor/pathable-styles/imports/test.m.css:3:1
W20160710-22:12:19.301(-3)? (STDERR)     at node_modules/meteor/pathable-styles/imports/test.m.css:3:1
W20160710-22:12:19.301(-3)? (STDERR)     at /Users/rafaelvidaurre/Code/pathable/pathable-admin/.meteor/local/build/programs/server/boot.js:297:10
W20160710-22:12:19.301(-3)? (STDERR)     at Array.forEach (native)
=> Exited with code: 8                        
=> Your application is crashing. Waiting for file change.
```

Package.js code contains (among other stuff):

```
Package.onUse(function(api) {
    api.versionsFrom('1.3.2.4');
    api.use('ecmascript');
    api.use('nathantreid:css-modules');
    api.mainModule('pathable-styles.js');
  });
```

pathable-styles.js contains:

```
import testStyles from './imports/test.m.css';

console.log(testStyles);
```

Any ideas? Thanks for the help

**Comment by RafaelVidaurre** [comment]
Fixed this somehow after re-doing the setup
