### ISSUE TITLE
Comments break compilation

### ISSUE THREAD

**Issue by RafaelVidaurre** [nathantreid/meteor-css-modules#63]
Adding `//` to a scss file throws:

```
=> Errors prevented startup:

   While processing files with nathantreid:css-modules (for target web.browser):
   /Users/rafaelvidaurre/.meteor/packages/nathantreid_css-modules/.2.1.3.fp41wz++os+web.browser+web.cordova/plugin.mss.os/npm/node_modules/meteor/mss/node_modules/postcss/lib/input.js:61:22:
   /Users/rafaelvidaurre/Code/pathable/pathable-app/packages/pathable-styles/imports/attendees-site/layout.m.scss:3:1: Unknown word
   at Input.error
   (/Users/rafaelvidaurre/.meteor/packages/nathantreid_css-modules/.2.1.3.fp41wz++os+web.browser+web.cordova/plugin.mss.os/npm/node_modules/meteor/mss/node_modules/postcss/lib/input.js:61:22)
   at Parser.unknownWord
   (/Users/rafaelvidaurre/.meteor/packages/nathantreid_css-modules/.2.1.3.fp41wz++os+web.browser+web.cordova/plugin.mss.os/npm/node_modules/meteor/mss/node_modules/postcss/lib/parser.js:457:26)
   at Parser.word
   (/Users/rafaelvidaurre/.meteor/packages/nathantreid_css-modules/.2.1.3.fp41wz++os+web.browser+web.cordova/plugin.mss.os/npm/node_modules/meteor/mss/node_modules/postcss/lib/parser.js:174:14)
   at Parser.loop
   (/Users/rafaelvidaurre/.meteor/packages/nathantreid_css-modules/.2.1.3.fp41wz++os+web.browser+web.cordova/plugin.mss.os/npm/node_modules/meteor/mss/node_modules/postcss/lib/parser.js:60:26)
   at parse (/Users/rafaelvidaurre/.meteor/packages/nathantreid_css-modules/.2.1.3.fp41wz++os+web.browser+web.cordova/plugin.mss.os/npm/node_modules/meteor/mss/node_modules/postcss/lib/parse.js:26:12)
   at new LazyResult
   (/Users/rafaelvidaurre/.meteor/packages/nathantreid_css-modules/.2.1.3.fp41wz++os+web.browser+web.cordova/plugin.mss.os/npm/node_modules/meteor/mss/node_modules/postcss/lib/lazy-result.js:61:24)
   at Processor.process
   (/Users/rafaelvidaurre/.meteor/packages/nathantreid_css-modules/.2.1.3.fp41wz++os+web.browser+web.cordova/plugin.mss.os/npm/node_modules/meteor/mss/node_modules/postcss/lib/processor.js:34:16)
   at CssModulesProcessor.load (packages/mss/css-modules-processor.js:76:5)
   at packages/mss/css-modules-processor.js:33:10
   at tryCallTwo (/Users/rafaelvidaurre/.meteor/packages/meteor-tool/.1.3.3_1.5lvmrz++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/promise/lib/core.js:45:5)
   at doResolve (/Users/rafaelvidaurre/.meteor/packages/meteor-tool/.1.3.3_1.5lvmrz++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/promise/lib/core.js:200:13)
   at new Promise (/Users/rafaelvidaurre/.meteor/packages/meteor-tool/.1.3.3_1.5lvmrz++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/promise/lib/core.js:66:3)
   at CssModulesProcessor.processInternal (packages/mss/css-modules-processor.js:28:11)
   at CssModulesProcessor.process (packages/mss/css-modules-processor.js:18:26)
   at CssModulesBuildPlugin.processFile (packages/mss/css-modules-build-plugin.js:249:22)
   at Array.forEach (native)
   at CssModulesBuildPlugin.compileCssModules (packages/mss/css-modules-build-plugin.js:241:34)
   at CssModulesBuildPlugin.processFilesForTarget (packages/mss/css-modules-build-plugin.js:64:21)


=> Your application has errors. Waiting for file change.
```

**Comment by akanix42** [comment]
Can you verify that you have node-sass installed?
I experienced this myself not long ago; it was caused by not having scss processing enabled but not having node-sass installed, so I added an additional error message:

```
Error checking npm module: node-sass@3.x (required by nathantreid:css-modules): module not found. Please ensure you have installed the module; here is the command:
 meteor npm install node-sass --save-dev

=> Errors prevented startup:

   While processing files with nathantreid:css-modules (for target web.browser):

```

I'm not sure why you wouldn't be getting that error message, but that's so far the only time I've seen this happen. The comments will be stripped out automatically when node-sass runs, so if the comments are causing an error, node-sass is for some reason not processing that file.
If you're still experiencing issues, please post a repro and I'll happily take a look.

**Comment by RafaelVidaurre** [comment]
Okay update on this: I installed node-sass on the _package_ directory as well. No errors are shown now with comments _BUT_ if I use `//` any style after it doesn't get applied. If I use multy-line comments `/* */` stuff works though.

Cannot make a repro repo for now though :/!

**Comment by RafaelVidaurre** [comment]
This dissapeared after removing fourseven:scss from packages list

**Comment by akanix42** [comment]
How strange! When I add fourseven:scss to my main app (with nathantreid:css-modules included in the main app and SCSS compilation enabled), Meteor errors out. The same thing happens if I add `fourseven:scss` and `nathantreid:css-modules` to a local package.

```
   While determining active plugins:
   error: conflict: two packages included in test (nathantreid:css-modules and fourseven:scss) are both trying to handle
   *.scss
```

**Comment by akanix42** [comment]
So to clarify, this eror was because you had both fourseven:scss and nathantreid:css-modules being used to process .scss files in a local package, but Meteor for some reason didn't display a conflict error?

**Comment by RafaelVidaurre** [comment]
This had to do with a script we were using to recursively call `addFiles` on each file in the package. Through that method this was happening for some reason. So not sure if actually related to the package in the end. There were just too many variables to correctly diagnose this
