### ISSUE TITLE
Errors on scss files do not explain what happened

### ISSUE THREAD

**Issue by RafaelVidaurre** [nathantreid/meteor-css-modules#64]
Yet another thing is happening to me. For some reason, sass errors dunno throw an explanation of what is failing.

For example, if I reference  a variable or mixin that doesn't exist, I get:

```
=> Client modified -- refreshing (x2)
/Users/rafaelvidaurre/.meteor/packages/meteor-tool/.1.3.3_1.5lvmrz++os.osx.x86_64+web.browser+web.cordova/ mt-os.osx.x86_64/isopackets/ddp/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:165
      throw error;
            ^
TypeError: Cannot set property './header.scss.js' of undefined
    at ImportScanner._checkSourceAndTargetPaths (/tools/isobuild/import-scanner.js:275:7)
    at /tools/isobuild/import-scanner.js:178:12
    at Array.forEach (native)
    at ImportScanner.addInputFiles (/tools/isobuild/import-scanner.js:177:11)
    at /tools/isobuild/compiler-plugin.js:1011:15
    at Array.forEach (native)
    at Function.computeJsOutputFilesMap (/tools/isobuild/compiler-plugin.js:982:19)
    at ClientTarget._emitResources (/tools/isobuild/bundler.js:925:8)
    at /tools/isobuild/bundler.js:696:12
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ClientTarget.make (/tools/isobuild/bundler.js:687:18)
    at /tools/isobuild/bundler.js:2533:14
    at /tools/isobuild/bundler.js:2622:20
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/rafaelvidaurre/.meteor/packages/meteor-tool/.1.3.3_1.5lvmrz++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/bundler.js:2621:7
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2514:31)
    at /tools/runners/run-app.js:591:36
    at Function.run (/tools/tool-env/profile.js:489:12)
    at bundleApp (/tools/runners/run-app.js:581:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:831:35)
    at AppRunner._fiber (/tools/runners/run-app.js:887:28)
    at /tools/runners/run-app.js:411:12

```

Thanks for taking the time to reading through all of the issues I've posted

**Comment by akanix42** [comment]
Can you update to v2.1.4 and see if that gives you the info you are looking for?

**Comment by RafaelVidaurre** [comment]
@nathantreid having a look

**Comment by RafaelVidaurre** [comment]
@nathantreid Yes, extremely useful now. Thanks!

**Comment by RafaelVidaurre** [comment]
(Line number is missing though, but other than that this is much better
