### ISSUE TITLE
Error: Cannot find module './data/character-class-escape-sets.js' on Windows 10

### ISSUE THREAD

**Issue by jason-curtis** [nathantreid/meteor-css-modules#71]
This issue has been posted previously with more detail here: https://forums.meteor.com/t/meteor-build-error-cannot-find-module/28929 by @Spiralis - I'm having the same issue which is apparently something to do with certain Meteor installations on Windows machines. Any help would be much appreciated.

Error message from `meteor run`:

```
   Processing files with nathantreid:css...  /
/~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Processing Step: Babel compilation
Unable to compile imports/ui/App.scss
Error: Cannot find module './data/character-class-escape-sets.js'
Source:
// <start of file>
 import modules from 'meteor/modules';
modules.addStyles("ul {\n  display: inline; }\n/*# sourceMappingURL=App.scss.map */");
const styles = {};
export { styles as default, styles };
// <end of file>

/~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
=> Errors prevented startup:

   While processing files with nathantreid:css-modules (for target web.browser):
   module.js:325:15: Cannot find module './data/character-class-escape-sets.js'
   at Function.Module._resolveFilename (module.js:325:15)
   at Function.Module._load (module.js:276:25)
   at Module.require (module.js:353:17)
   at require (internal/module.js:12:17)
   at Object.<anonymous>
   (C:\Users\Jason\AppData\Local\.meteor\packages\nathantreid_css-modules\2.2.2\plugin.mss.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babel-preset-meteor\node_modules\babel-plugin-transform-es2015-unicode-regex\node_modules\regexpu-core\rewrite-pattern.js:5:19)
   at Module._compile (module.js:409:26)
   at Object.Module._extensions..js (module.js:416:10)
   at Module.load (module.js:343:32)
   at Module.Mp.load
   (C:\Users\Jason\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
   at Function.Module._load (module.js:300:12)
   at Module.require (module.js:353:17)
   at require (internal/module.js:12:17)
   at Object.<anonymous>
   (C:\Users\Jason\AppData\Local\.meteor\packages\nathantreid_css-modules\2.2.2\plugin.mss.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babel-preset-meteor\node_modules\babel-plugin-transform-es2015-unicode-regex\lib\index.js:19:44)
   at Module._compile (module.js:409:26)
   at Object.Module._extensions..js (module.js:416:10)
   at Module.load (module.js:343:32)
   at Module.Mp.load
   (C:\Users\Jason\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
   at Function.Module._load (module.js:300:12)
   at Module.require (module.js:353:17)
   at require (internal/module.js:12:17)
   at Object.<anonymous>
   (C:\Users\Jason\AppData\Local\.meteor\packages\nathantreid_css-modules\2.2.2\plugin.mss.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babel-preset-meteor\index.js:33:5)
   at Module._compile (module.js:409:26)
   at Object.Module._extensions..js (module.js:416:10)
   at Module.load (module.js:343:32)
   at Module.Mp.load
   (C:\Users\Jason\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
   at Function.Module._load (module.js:300:12)
   at Module.require (module.js:353:17)
   at require (internal/module.js:12:17)
   at Object.getDefaults
   (C:\Users\Jason\AppData\Local\.meteor\packages\nathantreid_css-modules\2.2.2\plugin.mss.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\options.js:30:15)
   at getDefaultOptions (packages/babel-compiler/babel.js:9:1)
   at Object.Babel.compile (packages/babel-compiler/babel.js:25:1)
   at tryBabelCompile (packages/mss/css-modules-build-plugin.js:307:18)
   at CssModulesBuildPlugin.addCompileResult (packages/mss/css-modules-build-plugin.js:294:11)
   at packages/mss/css-modules-build-plugin.js:252:12
   at
   C:\Users\Jason\AppData\Local\.meteor\packages\less\2.6.5\plugin.compileLessBatch.os\npm\node_modules\meteor\promise\node_modules\meteor-promise\fiber_pool.js:32:39
```

**Comment by jason-curtis** [comment]
Just tracked down a workaround:

I inspected the stack trace and found the location where it was looking for the missing file 'data/character-class-escape-sets.js'. For me that was C:\Users\Jason\AppData\Local\.meteor\packages\nathantreid_css-modules\2.2.2\plugin.mss.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babel-preset-meteor\node_modules\babel-plugin-transform-es2015-unicode-regex\node_modules\regexpu-core. When I navigated there and looked in the "data" folder, I saw that there was no "character-class-escape-sets.js" file.

However, I noticed that the regexpu-core package was also installed at my project's ".meteor\local\dev_bundle\lib\node_modules\regexpu-core", and in that location the "character-class-escape-sets.js" file was present in the data folder.

Inspecting the two package.jsons, I saw that the regexpu-core package pulled in by css-modules (the one missing the 'character-class-escape-sets.js' file) was only version 1.0.0, while the other one was version 2.0.0. Presumably the version difference explains why the expected file was missing.

I was able to (temporarily?) fix this problem by copying the missing file to the correct location. However, presumably there could be a more permanent (and less hacky) fix by somehow fixing dependencies.

**Comment by akanix42** [comment]
I've updated to the latest package versions - can you try nathantreid:css-modules@2.4.0-beta.1?

**Comment by jason-curtis** [comment]
Thanks for the response!
with the new version I'm getting a different error message:

```
   While processing files with nathantreid:css-modules (for target web.browser):
   native: ENOENT: no such file or directory, scandir
   'D:\node_modules\meteor\mss\node_modules\node-sass\vendor'
   at Error (native)
   at Object.fs.readdirSync (fs.js:808:18)
   at Object.getInstalledBinaries (node_modules/meteor/mss/node_modules/node-sass/lib/extensions.js:119:1)
   at foundBinariesList (node_modules/meteor/mss/node_modules/node-sass/lib/errors.js:20:1)
   at foundBinaries (node_modules/meteor/mss/node_modules/node-sass/lib/errors.js:15:1)
   at Object.module.exports.missingBinary (node_modules/meteor/mss/node_modules/node-sass/lib/errors.js:45:1)
   at meteorInstall.node_modules.meteor.mss.node_modules.node-sass.lib.index.js
   (node_modules/meteor/mss/node_modules/node-sass/lib/index.js:15:1)
   at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
   at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
   at new ScssProcessor (packages/mss/scss-processor.js:12:55)
   at CssModulesBuildPlugin._setupPreprocessors (packages/mss/css-modules-build-plugin.js:104:31)
   at CssModulesBuildPlugin.processFilesForTarget (packages/mss/css-modules-build-plugin.js:53:10)
```

Not sure why it's expecting there to be a `D:\node_modules` directory at all as my project is in a different subdirectory of `D:\`

**Comment by wojtkowiak** [comment]
@nathantreid any idea why from version `2.3.0` your package has grown by ~180mb?
Here is a screenshot for `2.4.0` but the same applies to `2.3.0`.
![size](https://cloud.githubusercontent.com/assets/8668306/19515864/98fdd698-95f9-11e6-815d-ebd1b57d5ae6.png)
On Windows I have waited for 3 hours for the package to be extracted...

**Comment by wojtkowiak** [comment]
All those extra mb are in `.npm/node_modules` - previously this dir was empty.

**Comment by akanix42** [comment]
I'll take a look, thanks for the heads up.

**Comment by akanix42** [comment]
I messed up the publish of 2.3.0. The package is back down to a normal size now in nathantreid:css-modules@2.3.1. Please give that a try.

**Comment by wojtkowiak** [comment]
@nathantreid, thanks will try it tomorrow.

**Comment by akanix42** [comment]
I'm going to close this since from what I know it should have been resolved and there hasn't been any activity in a while. Feel free to reopen it if you need to.
