### ISSUE TITLE
Issue with meteor 1.4.2

### ISSUE THREAD

**Issue by Phaze1D** [nathantreid/meteor-css-modules#74]
I get this error message when I try to add the package to meteor verison 1.4.2

/Users/david/.meteor/packages/meteor-tool/.1.4.2.5dcm3r++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/ddp/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^

Error: EBADF: bad file descriptor, fstat
    at Error (native)
 => awaited here:
    at Promise.await (/Users/david/.meteor/packages/meteor-tool/.1.4.2.5dcm3r++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/ddp/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:39:12)
    at Object.wrapper [as readFile](/tools/fs/files.js:1522:32)
    at /tools/isobuild/isopack.js:979:15
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/david/.meteor/packages/meteor-tool/.1.4.2.5dcm3r++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Isopack._loadUnibuildsFromPath (/tools/isobuild/isopack.js:965:7)
    at /tools/packaging/tropohouse.js:521:21
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/david/.meteor/packages/meteor-tool/.1.4.2.5dcm3r++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/packaging/tropohouse.js:520:13
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at /tools/packaging/tropohouse.js:515:22
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at Object.download (/tools/packaging/tropohouse.js:427:20)
    at /tools/packaging/tropohouse.js:600:22
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at [object Object].downloadPackagesMissingFromMap (/tools/packaging/tropohouse.js:597:20)
    at /tools/project-context.js:776:25
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at /tools/project-context.js:775:20
    at /tools/packaging/catalog/catalog.js:100:5
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (/tools/packaging/catalog/catalog.js:99:31)
    at ProjectContext._downloadMissingPackages (/tools/project-context.js:774:13)
    at /tools/project-context.js:268:9
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._completeStagesThrough (/tools/project-context.js:258:18)
    at /tools/project-context.js:250:12
    at Function.run (/tools/tool-env/profile.js:490:12)
    at ProjectContext.prepareProjectForBuild (/tools/project-context.js:249:13)
    at /tools/cli/commands-packages.js:2036:20
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Command.func (/tools/cli/commands-packages.js:2035:27)
    at /tools/cli/main.js:1454:23

**Comment by croogie** [comment]
The same here! +1

**Comment by tjramage** [comment]
I also get the same problem. Have reinstalled Meteor twice. You can reproduce this by creating a new Meteor project and adding this package.

**Comment by tjramage** [comment]
Managed to find a workaround for the meantime. I installed node v7 (with NVM) and set it as my default node alias. Downloaded the contents of this repo and placed it in `/packages/nathantreid_css-modules` folder. Finally had to add `"ignorePaths": ["node_modules"]` to the CSS modules config in my `package.json` (it was picking up SCSS tests within the package itself!?) and now it's finally working.

Would be nice to get this working properly through the usual means though!

**Comment by mmskvortsov** [comment]
I get the same error. Mac Sierra 10.12.1, Meteor 1.4.2

**Comment by akanix42** [comment]
I haven't been able to reproduce this, but I did mess up the publish of 2.3.0. Please give nathantreid:css-modules@2.3.1 a try. Thanks!

**Comment by Phaze1D** [comment]
Yup it work. I think it was 2.3.0
Thanks
