### ISSUE TITLE
Unable to start meteor

### ISSUE THREAD

**Issue by nodegin** [nathantreid/meteor-css-modules#8]
Here's the log:

```
=> Errors prevented startup:                  

   While processing files with nathantreid:css-modules (for target web.browser):
   error: Can't load npm module 'postcss-simple-vars' from
   packages/nathantreid_css-modules-mss-compiler.js. Check your Npm.depends().
   plugins-loader.js:43:35: plugin postcss-simple-vars was not found by NPM!
   at plugins-loader.js:43:35
   at forEach (packages/ramda_ramda/upstream/dist/ramda.js:1874:1)
   at packages/ramda_ramda/upstream/dist/ramda.js:390:1
   at Object.f2 (packages/ramda_ramda/upstream/dist/ramda.js:434:1)
   at loadPlugins (plugins-loader.js:41:4)
   at PluginsLoader.load (plugins-loader.js:23:10)
   at CssModulesBuildPlugin.processFilesForTarget (css-modules-build-plugin.js:14:37)


=> Your application has errors. Waiting for file change.
```

I am trying to use this plugin with `kadira:flow-router-ssr` and `kadira:react-layout` for Meteor's universal application,

but I can't get css modules to be working, thanks for helping!

**Comment by akanix42** [comment]
When I've seen that error in the past it means you are referencing the postcss-simple-vars plugin in your [css-modules.json](https://github.com/nathantreid/meteor-css-modules-test/blob/master/config/css-modules.json) file, but it is not included in your [packages.json](https://github.com/nathantreid/meteor-css-modules-test/blob/master/packages.json) file.

It's not a [required plugin](https://github.com/nathantreid/meteor-css-modules#postcss-plugins), so you can simply remove it if you don't want it.

I can see that my instructions for loading postcss plugins were unclear, so I've updated the documentation as well: 8bc034411390dfb9a60971436ce37d09ca849490.

Make sure to restart Meteor after modifying those files, and let me know if that does the trick!

**Comment by nodegin** [comment]
Hello, I have tried to place the `packages.json` in the root directory of my project

![2016-03-22 1 10 34](https://cloud.githubusercontent.com/assets/8536244/13942629/7c887560-f02f-11e5-9d59-fabc7ed269a4.png)

But still getting the same error:

```
=> Errors prevented startup:                  

   While processing files with nathantreid:css-modules-mss (for target
   web.browser):
   error: Can't load npm module 'postcss-simple-vars' from
   packages/nathantreid_css-modules-mss-compiler.js. Check your Npm.depends().
   plugins-loader.js:43:35: plugin postcss-simple-vars was not found by NPM!
   at plugins-loader.js:43:35
   at forEach (packages/ramda_ramda/upstream/dist/ramda.js:1874:1)
   at packages/ramda_ramda/upstream/dist/ramda.js:390:1
   at Object.f2 (packages/ramda_ramda/upstream/dist/ramda.js:434:1)
   at loadPlugins (plugins-loader.js:41:4)
   at PluginsLoader.load (plugins-loader.js:23:10)
   at CssModulesBuildPlugin.processFilesForTarget
   (css-modules-build-plugin.js:14:37)


=> Your application has errors. Waiting for file change.
^C
```

Here's the content inside my `packages.json`:

``` json
{
  "postcss-simple-vars": "^1.2.0",
  "postcss-nested-props": "^1.1.0",
  "postcss-modules-values": "^1.1.2",
  "postcss-nested": "^1.0.0",
  "postcss-selector-not": "^2.0.0",
  "postcss-modules-local-by-default": "^1.0.1",
  "postcss-modules-scope": "^1.0.0"
}
```

And the `config/css-modules.json`:

``` json
{
  "version": "0.5.0",
  "postcssPlugins": [
    {
      "package": "postcss-simple-vars"

    },
    {
      "package": "postcss-nested-props"

    },
    {
      "package": "postcss-modules-values"

    },
    {
      "package": "postcss-nested"

    },
    {
      "package": "postcss-selector-not"

    },
    {
      "package": "postcss-modules-local-by-default"

    },
    {
      "package": "postcss-modules-scope"

    }
  ]
}
```

**Comment by nodegin** [comment]
I have fixed this issue by running `meteor add meteorhacks:npm`
