### ISSUE TITLE
explicitIncludes option doesn't work

### ISSUE THREAD

**Issue by akanix42** [nathantreid/meteor-css-modules#92]
Reported by @neoromantic (moved from #83 )
So, when I do that:

```
 25   "cssModules": {
 26     "postcssPlugins": {
 27       "postcss-import": {},
 28       "postcss-mixins": {},
 29       "postcss-each": {},
 30       "postcss-cssnext": {},
 31       "postcss-simple-vars": {},
 32       "postcss-modules-local-by-default": {},
 33       "postcss-modules-extract-imports": {},
 34       "postcss-modules-scope": {}
 35     },
 36     "extensions": [
 37       "scss",
 38       "css"
 39     ],
 40     "ignorePaths": [
 41       "node_modules"
 42     ],
 43     "explicitIncludes": ["node_modules/react-toolbox/lib"]
 44   }
```
I get that:

```
=> Errors prevented startup:                  
   
   While processing files with nathantreid:css-modules (for target web.browser):
   native: Not a string or buffer
   at TypeError (native)
   at Hash.update (crypto.js:70:16)
   at sha1 (packages/mss/sha1.js:5:8)
   at IncludedFile.getSourceHash (packages/mss/included-file.js:76:12)
   at CssModulesBuildPlugin.getCacheKey (packages/mss/css-modules-build-plugin.js:268:47)
   at packages/caching-compiler/multi-file-caching-compiler.js:91:55
   at Array.forEach (native)
   at CssModulesBuildPlugin.processFilesForTarget (packages/caching-compiler/multi-file-caching-compiler.js:88:16)
   at CssModulesBuildPlugin.processFilesForTarget (packages/mss/css-modules-build-plugin.js:58:5)
```

**Comment by akanix42** [comment]
This was fixed in v2.5.0.
